lo_address: 10.0.0.1/32
interfaces:
  - name: "swp1"
    address: "10.1.1.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.1.1/30"
    connected_to: "spine02"

ospf_router_id: 10.0.0.1
ospf_networks:
  - subnet: "10.0.0.1/32"
  - subnet: "10.1.1.0/30"
  - subnet: "10.2.1.0/30"