---
lo_address: 10.0.0.3/32
interfaces:
  - name: "swp1"
    address: "10.1.3.1/30"
    connected_to: "spine01"
  - name: "swp2"
    address: "10.2.3.1/30"
    connected_to: "spine02"
  - name: "swp3"
    address: "10.0.30.1/30"
    connected_to: "vm03"
    vrf: choubidou

ospf_router_id: 10.0.0.3
ospf_networks:
  - subnet: "10.0.0.3/32"
  - subnet: "10.1.3.0/30"
  - subnet: "10.2.3.0/30"
  - subnet: "10.0.30.0/30"

vnix:
  - id: 10020
    rt: 20
  - id: 10010
    rt: 10
  - id: 10040
    rt: 40

vlans:
  - id: 10
    vrf: choubidou
  - id: 20
    vrf: choubidou
  - id: 30
    ip: "10.1.130.1/24"
    vrf: choubidou
  - id: 40
    vrf: choubidou

vrfs:
  - id: choubidou
    vni: 10040