- name: Include spines frr configuration tasks for ospf and pim
  include_tasks: spines.yml
  when: inventory_hostname in groups['spines']

- name: Include leaves frr configuration tasks for ospf and pim
  include_tasks: leaves.yml
  when: inventory_hostname in groups['leaves']
